### PR TITLE
Add button to panel "Send Cash" for inserting max send-able amount

### PR DESCRIPTION
**Pull request by cypheron**
This commit adds a new button to the "Send Cash" panel which allows automatic fill-in of the "Amount to send" field to the maximum send-able amount for the selected wallet.

The maximum send-able amount is the wallets balance minus fee.

swing

### CODE REVIEW

**Comment by TheTrunk** [comment]
Sometimes I am not obtaining correct amount - precision thing as demonstrated on the picture
maxWrongDec

Thank you for this great PR!

**Comment by cypheron** [comment]
@TheTrunk I force-pushed a change to cut off the value after 8 decimals.

**Comment by TheTrunk** [comment]
The precision is now correct. But can we get rid of the trailing 0s? So the string has only the neccessary decimal places

**Comment by cypheron** [comment]
@TheTrunk Force-pushed another update. Should be good to go now. Now using the same approach to retrieve balance as for the combobox (using getBalanceForAddress() function which returns the correctly rounded value) and outputting this number as-is (without trailing zeros).

**Comment by Cabecinha84** [comment]
Hello cypheron, first of all, thank you very much for your contribution.
I have checked your code, and you should change two things:
- Where you have "Double.toString(" it should be "new DecimalFormat("########0.00######").format("
- And clientCaller should be changed to final on the constructor.
Check attached print screen.

Waiting for your change. Again, thank you very much.

image

**Comment by cypheron** [comment]
@Cabecinha84 Thanks for the input! I went over to using `DecimalFormat` instead of `toString`, which also made the use of using clientcaller obsolete (using displayed value from combobox).

**Pull request merged**
